name: 'GitHub Label Manager'
author: 'Isaac Muse'
description: 'Simple label manager for GitHub'
inputs:
  token:
    description: 'GitHub access token for managing labels'
    required: true
    default: ''
  mode:
    description: 'Set mode to run label manager in: delete (deletes labels not in list), normal (leaves orphaned labels).'
    required: false
    default: 'normal'
  file:
    description: 'JSON file containing the labels. Default is .github/labels.json'
    required: false
    default: '.github/labels.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'green'
