name: 'GitHub Label Manager'
author: 'Isaac Muse'
description: 'Simple label manager for GitHub'
inputs:
  token:
    description: 'GitHub access token for managing labels'
    required: true
    default: ''
  mode:
    description: 'Set mode to run label manager in: delete (deletes labels not in list), normal (leaves orphaned labels).'
    required: false
    default: 'normal'
  file:
    description: 'YAML file containing the labels. Default is .github/labels.yml'
    required: false
    default: '.github/labels.yml'
  debug:
    description: 'Debug will run the label syncer without applying changes. Set to "enable" to enable.'
    required: false
    default: 'disable'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'green'
