name: labels

on:
  push:
    branches:
      - 'feature/yaml'

jobs:
  label-sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Sync labels
      uses: facelessuser/label-mgr-action@feature/yaml
      with:
        token: ${{ secrets.GH_TOKEN }}
        mode: 'delete'
        debug: 'enable'
        file: '.github/labels.yml'
